./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install atom-dark-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install atom-dark-ui
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install atom-light-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install atom-light-ui
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install base16-tomorrow-dark-theme
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install base16-tomorrow-light-theme
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install one-dark-ui
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install one-light-ui
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install one-dark-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install one-light-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install solarized-dark-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install solarized-light-syntax
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install about
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install archive-view
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autocomplete-atom-api
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autocomplete-css
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autocomplete-html
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autocomplete-plus
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autocomplete-snippets
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autoflow
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install autosave
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install background-tips
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install bookmarks
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install bracket-matcher
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install command-palette
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install deprecation-cop
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install dev-live-reload
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install encoding-selector
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install exception-reporting
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install find-and-replace
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install fuzzy-finder
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install git-diff
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install go-to-line
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install grammar-selector
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install image-view
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install incompatible-packages
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install keybinding-resolver
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install line-ending-selector
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install link
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install markdown-preview
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install metrics
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install notifications
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install open-on-github
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install package-generator
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install settings-view
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install snippets
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install spell-check
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install status-bar
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install styleguide
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install symbols-view
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install tabs
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install timecop
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install tree-view@0.214.1
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install update-package-dependencies
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install welcome
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install whitespace
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install wrap-guide
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-c
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-clojure
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-coffee-script
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-csharp
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-css
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-gfm
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-git
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-go
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-html
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-hyperlink
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-java
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-javascript
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-json
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-less
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-make
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-mustache
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-objective-c
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-perl
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-php
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-property-list
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-python
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-ruby
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-ruby-on-rails
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-sass
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-shellscript
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-source
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-sql
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-text
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-todo
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-toml
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-xml
./out/atom-1.15.0-armv7l/resources/app/apm/bin/apm install language-yaml
