./resources/app/apm/bin/apm install atom-dark-syntax
./resources/app/apm/bin/apm install atom-dark-ui
./resources/app/apm/bin/apm install atom-light-syntax
./resources/app/apm/bin/apm install atom-light-ui
./resources/app/apm/bin/apm install base16-tomorrow-dark-theme
./resources/app/apm/bin/apm install base16-tomorrow-light-theme
./resources/app/apm/bin/apm install one-dark-ui
./resources/app/apm/bin/apm install one-light-ui
./resources/app/apm/bin/apm install one-dark-syntax
./resources/app/apm/bin/apm install one-light-syntax
./resources/app/apm/bin/apm install solarized-dark-syntax
./resources/app/apm/bin/apm install solarized-light-syntax
./resources/app/apm/bin/apm install about
./resources/app/apm/bin/apm install archive-view
./resources/app/apm/bin/apm install autocomplete-atom-api
./resources/app/apm/bin/apm install autocomplete-css
./resources/app/apm/bin/apm install autocomplete-html
./resources/app/apm/bin/apm install autocomplete-plus
./resources/app/apm/bin/apm install autocomplete-snippets
./resources/app/apm/bin/apm install autoflow
./resources/app/apm/bin/apm install autosave
./resources/app/apm/bin/apm install background-tips
./resources/app/apm/bin/apm install bookmarks
./resources/app/apm/bin/apm install bracket-matcher
./resources/app/apm/bin/apm install command-palette
./resources/app/apm/bin/apm install deprecation-cop
./resources/app/apm/bin/apm install dev-live-reload
./resources/app/apm/bin/apm install encoding-selector
./resources/app/apm/bin/apm install exception-reporting
./resources/app/apm/bin/apm install find-and-replace
./resources/app/apm/bin/apm install fuzzy-finder
./resources/app/apm/bin/apm install git-diff
./resources/app/apm/bin/apm install go-to-line
./resources/app/apm/bin/apm install grammar-selector
./resources/app/apm/bin/apm install image-view
./resources/app/apm/bin/apm install incompatible-packages
./resources/app/apm/bin/apm install keybinding-resolver
./resources/app/apm/bin/apm install line-ending-selector
./resources/app/apm/bin/apm install link
./resources/app/apm/bin/apm install markdown-preview
./resources/app/apm/bin/apm install metrics
./resources/app/apm/bin/apm install notifications
./resources/app/apm/bin/apm install open-on-github
./resources/app/apm/bin/apm install package-generator
./resources/app/apm/bin/apm install settings-view
./resources/app/apm/bin/apm install snippets
./resources/app/apm/bin/apm install spell-check
./resources/app/apm/bin/apm install status-bar
./resources/app/apm/bin/apm install styleguide
./resources/app/apm/bin/apm install symbols-view
./resources/app/apm/bin/apm install tabs
./resources/app/apm/bin/apm install timecop
./resources/app/apm/bin/apm install tree-view@0.241.1
./resources/app/apm/bin/apm install update-package-dependencies
./resources/app/apm/bin/apm install welcome
./resources/app/apm/bin/apm install whitespace
./resources/app/apm/bin/apm install wrap-guide
./resources/app/apm/bin/apm install language-c
./resources/app/apm/bin/apm install language-clojure
./resources/app/apm/bin/apm install language-coffee-script
./resources/app/apm/bin/apm install language-csharp
./resources/app/apm/bin/apm install language-css
./resources/app/apm/bin/apm install language-gfm
./resources/app/apm/bin/apm install language-git
./resources/app/apm/bin/apm install language-go
./resources/app/apm/bin/apm install language-html
./resources/app/apm/bin/apm install language-hyperlink
./resources/app/apm/bin/apm install language-java
./resources/app/apm/bin/apm install language-javascript
./resources/app/apm/bin/apm install language-json
./resources/app/apm/bin/apm install language-less
./resources/app/apm/bin/apm install language-make
./resources/app/apm/bin/apm install language-mustache
./resources/app/apm/bin/apm install language-objective-c
./resources/app/apm/bin/apm install language-perl
./resources/app/apm/bin/apm install language-php
./resources/app/apm/bin/apm install language-property-list
./resources/app/apm/bin/apm install language-python
./resources/app/apm/bin/apm install language-ruby
./resources/app/apm/bin/apm install language-ruby-on-rails
./resources/app/apm/bin/apm install language-sass
./resources/app/apm/bin/apm install language-shellscript
./resources/app/apm/bin/apm install language-source
./resources/app/apm/bin/apm install language-sql
./resources/app/apm/bin/apm install language-text
./resources/app/apm/bin/apm install language-todo
./resources/app/apm/bin/apm install language-toml
./resources/app/apm/bin/apm install language-xml
./resources/app/apm/bin/apm install language-yaml
